### ISSUE TITLE
PKGBUILD中md5的问题

### ISSUE THREAD

**Issue by princevandev** [shmilee/vpn4zju#2]
亲测可用，不过PKGBUILD里面的md5是不是要改一下，现在是eeeeee，我修改为201c34d813f3564e27c3b93057ce2637以后可以正常makepkg

**Comment by shmilee** [comment]
改成SKIP吧，14年那会，我还不知道MD5可以写成 SKIP。
毕竟定版本commit之后，md5就变了。这是个鸡（source）和蛋（MD5）的问题。

**Comment by princevandev** [comment]
很棒！为学长打call~
